name: Build OSLANG EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: 코드 받기
        uses: actions/checkout@v4

      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 패키지 설치
        run: npm install

      - name: EXE 빌드
        run: npm run dist

      - name: EXE 업로드
        uses: actions/upload-artifact@v4
        with:
          name: OSLANG-Interpreter-EXE
          path: dist/*.exe
